import 'dart:async';
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:tidy/core/design/design.dart';
import 'package:tidy/core/di/service_locator.dart';
import 'package:tidy/core/feedback/feedback.dart';
import 'package:tidy/core/platform/app_data_access_service.dart';
import 'package:tidy/core/platform/system_bridge.dart';
import 'package:tidy/core/services/launch_items_service.dart';
import 'package:tidy/core/widgets/widgets.dart';
import 'package:tidy/features/protection/data/models/protection_finding.dart';
import 'package:tidy/features/protection/data/services/protection_service.dart';
import 'package:tidy/features/protection/presentation/widgets/finding_row.dart';
import 'package:tidy/features/protection/presentation/widgets/protection_summary.dart';
import 'package:tidy/features/shell/domain/app_destination.dart';

/// Protection: what starts itself, what your extensions can reach, and where
/// your apps came from.
///
/// **Not a `ScanView`, deliberately**, and for four separate reasons. The clean
/// bar disables itself when the selection is worth zero bytes, and every finding
/// here is a 2 KB plist or a zero-byte fact. `SafetyLevel.safe` means
/// "regenerated by macOS", so nothing here could ever be pre-ticked. `ScanBloc`
/// only knows how to move paths to the Trash, and the verbs here are *turn off*,
/// *reveal* and *check properly*. And a result tile headlined "6 KB" over
/// "Startup Items" is worse than no tile at all.
///
/// A `StatefulWidget` rather than a bloc, like Space Lens and for the same
/// reason: `ProtectionService` already holds the results and streams them, so a
/// bloc here would be three files forwarding a stream to a `setState`.
class ProtectionPage extends StatefulWidget {
  const ProtectionPage({super.key});

  @override
  State<ProtectionPage> createState() => _ProtectionPageState();
}

class _ProtectionPageState extends State<ProtectionPage> {
  final ProtectionService _service = locator<ProtectionService>();
  final LaunchItemsService _launchItems = locator<LaunchItemsService>();

  StreamSubscription<Map<ProtectionArea, ProtectionAreaResult>>? _run;
  Map<ProtectionArea, ProtectionAreaResult> _results = const {};

  ProtectionArea _area = ProtectionArea.startup;

  /// Rows with an action in flight, and the answers checks have come back with.
  final Set<String> _busy = {};
  final Map<String, String> _notes = {};

  @override
  void initState() {
    super.initState();
    _load();
  }

  @override
  void dispose() {
    _run?.cancel();
    super.dispose();
  }

  void _load({bool refresh = false}) {
    _run?.cancel();
    if (refresh) {
      _service.invalidate();
      _notes.clear();
    }
    _run = _service.run(refresh: refresh).listen((results) {
      if (mounted) setState(() => _results = results);
    });
  }

  bool get _busyOverall =>
      _results.isEmpty || _results.values.any((result) => result.loading);

  /// Everything examined, ignoring the traces section — those are three
  /// statements about this Mac rather than things that were checked, and
  /// counting them would inflate the number that is supposed to mean "we
  /// looked at this many things".
  int get _checked => [
    for (final entry in _results.entries)
      if (entry.key != ProtectionArea.traces) entry.value.findings.length,
  ].fold(0, (sum, count) => sum + count);

  int get _notable =>
      _results.values
          .expand((result) => result.findings)
          .where(
            (finding) =>
                finding.verdict == ProtectionVerdict.notable &&
                !_service.isIgnored(finding),
          )
          .length;

  int get _unverified =>
      _results.values
          .expand((result) => result.findings)
          .where((finding) => finding.verdict == ProtectionVerdict.unverified)
          .length +
      _results.values.fold(0, (sum, result) => sum + result.unreadable);

  @override
  Widget build(BuildContext context) {
    return ModuleScaffold(
      title: AppDestination.protection.label,
      subtitle: AppDestination.protection.blurb,
      scrollable: false,
      actions: [
        OutlineActionButton(
          icon: AppIcons.refresh,
          label: 'Check again',
          onPressed: _busyOverall ? null : () => _load(refresh: true),
        ),
      ],
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          const ProtectionCaveat(),
          const SizedBox(height: AppSpacing.lg),
          ProtectionSummary(
            checked: _checked,
            notable: _notable,
            unverified: _unverified,
            busy: _busyOverall,
          ),
          const SizedBox(height: AppSpacing.lg),
          SegmentedTabs(
            labels: [for (final area in ProtectionArea.values) area.label],
            selectedIndex: ProtectionArea.values.indexOf(_area),
            counts: [
              for (final area in ProtectionArea.values)
                // Null rather than zero while an area is still working: a "0"
                // beside a heading reads as "none found", which is a different
                // and, for another second or so, untrue statement.
                if (_results[area]?.loading ?? true)
                  null
                else
                  _results[area]!.findings.length,
            ],
            onChanged:
                (index) => setState(() => _area = ProtectionArea.values[index]),
          ),
          const SizedBox(height: AppSpacing.md),
          Expanded(child: _section()),
        ],
      ),
    );
  }

  Widget _section() {
    final result = _results[_area];

    if (result == null || (result.loading && result.findings.isEmpty)) {
      return Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const GaugeRing(size: 120),
            const SizedBox(height: AppSpacing.lg),
            Text(
              'Looking at ${_area.label.toLowerCase()}',
              style: context.text.titleS,
            ),
          ],
        ),
      );
    }

    if (result.findings.isEmpty) {
      return EmptyState(
        icon: _area.icon,
        title: 'Nothing to show here',
        message: _emptyMessage(),
      );
    }

    // Worth a look first, then what could not be checked, then the rest — the
    // ordinary majority is what scrolling is for.
    final findings = List.of(result.findings)..sort((a, b) {
      final rank = _rank(a).compareTo(_rank(b));
      if (rank != 0) return rank;
      return a.title.toLowerCase().compareTo(b.title.toLowerCase());
    });

    return TidyCard(
      padding: EdgeInsets.zero,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          if (_area == ProtectionArea.extensions) const _SafariNote(),
          Expanded(
            child: ListView.builder(
              padding: EdgeInsets.zero,
              itemCount: findings.length,
              itemBuilder: (context, index) {
                final finding = findings[index];
                return FindingRow(
                  finding: finding,
                  iconBytes: _iconFor(finding),
                  ignored: _service.isIgnored(finding),
                  busy: _busy.contains(finding.id),
                  note: _notes[finding.id],
                  onIgnore:
                      (ignored) => setState(
                        () => _service.setIgnored(finding, ignored: ignored),
                      ),
                  onAction: (action) => _act(finding, action),
                );
              },
            ),
          ),
        ],
      ),
    );
  }

  int _rank(ProtectionFinding finding) {
    if (_service.isIgnored(finding)) return 3;
    return switch (finding.verdict) {
      ProtectionVerdict.notable => 0,
      ProtectionVerdict.unverified => 1,
      ProtectionVerdict.ordinary => 2,
    };
  }

  Uint8List? _iconFor(ProtectionFinding finding) {
    final path = finding.appPath;
    if (path == null) return null;
    return _launchItems.icons[path];
  }

  String _emptyMessage() => switch (_area) {
    ProtectionArea.startup =>
      'Nothing on this Mac is set to start itself outside macOS’s own items, '
          'which Tidy does not touch.',
    ProtectionArea.extensions =>
      'No extensions in Chrome, Brave, Edge or Firefox. Safari is not covered — '
          'see the note above.',
    ProtectionArea.apps =>
      'No applications outside macOS’s own were found to look at.',
    ProtectionArea.traces => 'Nothing to report.',
  };

  Future<void> _act(ProtectionFinding finding, ProtectionAction action) async {
    switch (action) {
      case ProtectionAction.reveal:
        if (finding.path != null) {
          await SystemBridge.revealInFinder(finding.path!);
        }
      case ProtectionAction.openSettings:
        await SystemBridge.openSettingsPane('Privacy_AllFiles');
      case ProtectionAction.openApps:
        if (mounted) context.go(AppDestination.applications.path);
      case ProtectionAction.allowBrowserAccess:
        await _askForBrowserAccess();
      case ProtectionAction.enable:
      case ProtectionAction.disable:
        await _toggle(finding, enable: action == ProtectionAction.enable);
      case ProtectionAction.remove:
        await _remove(finding);
      case ProtectionAction.validate:
        await _check(
          finding,
          run: () => _service.validate(finding),
          good:
              'The seal is intact — every file is as its developer signed it.',
        );
      case ProtectionAction.assess:
        await _check(
          finding,
          run: () => _service.assess(finding),
          good: 'macOS would open this without asking you first.',
        );
    }
  }

  /// Puts macOS's dialog up, having just explained what it is for.
  ///
  /// The explanation is the row this button sits on. That order is the rule in
  /// `AppDataAccessService`, and the reason the page does not simply read the
  /// browser folders when it opens — with this permission the first read *is*
  /// the request, and a dialog nobody was expecting is what this app's own copy
  /// calls indistinguishable from malware.
  Future<void> _askForBrowserAccess() async {
    final granted = await locator<AppDataAccessService>().request();
    if (!mounted) return;

    if (granted) {
      _load(refresh: true);
    } else {
      context.toastError(
        'macOS only asks once. You can change it under Privacy & Security → '
        'Files and Folders.',
        title: 'Not allowed',
      );
    }
  }

  Future<void> _toggle(
    ProtectionFinding finding, {
    required bool enable,
  }) async {
    setState(() => _busy.add(finding.id));
    final outcome = await _service.setStartupEnabled(finding, enabled: enable);
    if (!mounted) return;
    setState(() => _busy.remove(finding.id));

    if (outcome.ok) {
      context.toastSuccess(
        '${finding.title} will ${enable ? 'start' : 'not start'} itself.',
        title: enable ? 'Turned on' : 'Turned off',
      );
      _load(refresh: true);
    } else {
      context.toastError(
        outcome.message ?? 'macOS refused.',
        title: 'No change',
      );
    }
  }

  Future<void> _remove(ProtectionFinding finding) async {
    final confirmed = await TidyAlert.confirm(
      context,
      title: 'Remove ${finding.title}?',
      message:
          'It stops running and its file goes to the Trash, where you can put '
          'it back. Whatever installed it may put it back too, next time that '
          'app runs.',
      confirmLabel: 'Move to Trash',
      tone: FeedbackTone.danger,
      destructive: true,
      icon: AppIcons.delete,
      details: [
        if (finding.path != null)
          AlertDetail(title: finding.subtitle, detail: 'The file that goes'),
      ],
    );
    if (!confirmed || !mounted) return;

    setState(() => _busy.add(finding.id));
    final outcome = await _service.removeStartupItem(finding);
    if (!mounted) return;
    setState(() => _busy.remove(finding.id));

    if (outcome.ok) {
      context.toastSuccess(finding.title, title: 'Moved to Trash');
      _load(refresh: true);
    } else {
      context.toastError(
        outcome.message ?? 'macOS refused.',
        title: 'Could not remove it',
      );
    }
  }

  /// The two slow checks. Both are seconds, both are one row, and the answer
  /// stays beside the row rather than in a toast that has gone by the time the
  /// reader looks up.
  Future<void> _check(
    ProtectionFinding finding, {
    required Future<({bool ok, String? reason})> Function() run,
    required String good,
  }) async {
    setState(() {
      _busy.add(finding.id);
      _notes.remove(finding.id);
    });

    final verdict = await run();
    if (!mounted) return;

    setState(() {
      _busy.remove(finding.id);
      _notes[finding.id] = verdict.ok ? good : (verdict.reason ?? 'No answer.');
    });
  }
}

/// Said inside the section it applies to, not in a footnote.
class _SafariNote extends StatelessWidget {
  const _SafariNote();

  @override
  Widget build(BuildContext context) {
    final colors = context.colors;

    return Container(
      padding: const EdgeInsets.all(AppSpacing.lg),
      decoration: BoxDecoration(
        border: Border(bottom: BorderSide(color: colors.border)),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(AppIcons.info, size: 15, color: colors.textMuted),
          const SizedBox(width: AppSpacing.sm),
          Expanded(
            child: Text(
              'Safari is not covered. Its extensions are apps you install from '
              'the App Store rather than folders in a profile, and its settings '
              'sit behind a permission ${Brand.name} does not ask for.',
              style: context.text.caption,
            ),
          ),
        ],
      ),
    );
  }
}
