import 'package:flutter/foundation.dart';

/// How confident we are that removing something is a good idea.
///
/// This decides what is pre-selected, which is the most consequential UX
/// decision in a cleaner: everything a user removes without reading was
/// pre-selected by us.
enum SafetyLevel {
  /// Regenerated by macOS or the owning app. Pre-selected.
  safe,

  /// Probably fine, but worth a glance. Not pre-selected.
  review,

  /// User data, or irreversible. Never pre-selected, and confirmed separately.
  risky;

  bool get preselected => this == SafetyLevel.safe;
}

/// One reviewable finding.
///
/// Recursive on purpose: a module returns a tree (category → subcategory →
/// item) and the same widgets render every module. The top-level children
/// become the result tiles; their descendants become the review tree.
@immutable
class ScanNode {
  const ScanNode({
    required this.id,
    required this.title,
    this.subtitle,
    this.paths = const [],
    this.sizeBytes = 0,
    this.safety = SafetyLevel.review,
    this.requiresAdmin = false,
    this.sharesStorage = false,
    this.itemCount,
    this.icon,
    this.detail,
    this.children = const [],
  });

  /// Stable across rescans, so selection survives a refresh. Usually the path.
  final String id;

  final String title;

  /// Where it lives, with `$HOME` collapsed to `~`.
  final String? subtitle;

  /// Everything removing this node would touch. Empty for pure grouping nodes.
  final List<String> paths;

  /// Allocated bytes (`st_blocks * 512`), never logical size — a sparse file
  /// like Docker.raw reports 64 GB logically while occupying 8.
  ///
  /// Ignored for group nodes, which sum their children instead.
  final int sizeBytes;

  final SafetyLevel safety;

  /// Lives somewhere only root can write. Shown and explained, but not
  /// removable until the privileged helper exists.
  final bool requiresAdmin;

  /// An APFS clone or hardlink: the bytes are shared, so deleting this frees
  /// nothing. Reporting it is the difference between trustworthy and not.
  final bool sharesStorage;

  /// Overrides the derived leaf count, for nodes that summarise a collapsed
  /// long tail.
  final int? itemCount;

  final Uint8List? icon;

  /// One plain-language line explaining what this is and why it's safe to go.
  final String? detail;

  final List<ScanNode> children;

  bool get isLeaf => children.isEmpty;

  bool get isRemovable => paths.isNotEmpty && !requiresAdmin;

  /// Allocated bytes for this node and everything under it.
  int get totalBytes => isLeaf
      ? sizeBytes
      : children.fold<int>(0, (sum, child) => sum + child.totalBytes);

  /// Bytes that would actually be reclaimed — excludes cloned/hardlinked data
  /// and anything we can't remove yet.
  int get reclaimableBytes {
    if (isLeaf) return (sharesStorage || requiresAdmin) ? 0 : sizeBytes;
    return children.fold<int>(0, (sum, child) => sum + child.reclaimableBytes);
  }

  int get leafCount =>
      itemCount ??
      (isLeaf ? 1 : children.fold<int>(0, (sum, child) => sum + child.leafCount));

  /// Every leaf under this node, depth first.
  Iterable<ScanNode> get leaves sync* {
    if (isLeaf) {
      yield this;
    } else {
      for (final child in children) {
        yield* child.leaves;
      }
    }
  }

  /// This node and all its descendants.
  Iterable<ScanNode> get selfAndDescendants sync* {
    yield this;
    for (final child in children) {
      yield* child.selfAndDescendants;
    }
  }

  /// The strictest safety level anywhere in this subtree, so a group can't look
  /// safer than its contents.
  SafetyLevel get effectiveSafety {
    if (isLeaf) return safety;
    var worst = SafetyLevel.safe;
    for (final leaf in leaves) {
      if (leaf.safety.index > worst.index) worst = leaf.safety;
    }
    return worst;
  }

  /// True when any leaf below needs administrator rights.
  bool get containsAdminItems =>
      isLeaf ? requiresAdmin : leaves.any((leaf) => leaf.requiresAdmin);

  ScanNode copyWith({
    String? title,
    String? subtitle,
    List<String>? paths,
    int? sizeBytes,
    SafetyLevel? safety,
    bool? requiresAdmin,
    bool? sharesStorage,
    int? itemCount,
    Uint8List? icon,
    String? detail,
    List<ScanNode>? children,
  }) {
    return ScanNode(
      id: id,
      title: title ?? this.title,
      subtitle: subtitle ?? this.subtitle,
      paths: paths ?? this.paths,
      sizeBytes: sizeBytes ?? this.sizeBytes,
      safety: safety ?? this.safety,
      requiresAdmin: requiresAdmin ?? this.requiresAdmin,
      sharesStorage: sharesStorage ?? this.sharesStorage,
      itemCount: itemCount ?? this.itemCount,
      icon: icon ?? this.icon,
      detail: detail ?? this.detail,
      children: children ?? this.children,
    );
  }

  /// Sorted largest first, all the way down — the order every result list wants.
  ScanNode sortedBySize() {
    if (isLeaf) return this;
    final sorted = children.map((c) => c.sortedBySize()).toList()
      ..sort((a, b) => b.totalBytes.compareTo(a.totalBytes));
    return copyWith(children: sorted);
  }

  @override
  bool operator ==(Object other) => other is ScanNode && other.id == id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() => 'ScanNode($id, $totalBytes bytes, ${children.length} children)';
}
