import AppKit
import CryptoKit
import Foundation

/// Watches the system pasteboard and files what it sees into [ClipboardStore].
///
/// `NSPasteboard` has no change notification — Apple never shipped one — so the
/// only way to know is to poll `changeCount`, which is an integer read. At
/// 0.35 s that is far below anything measurable and fast enough that copying
/// and immediately opening the popover finds the item already there.
///
/// Owned by `AppDelegate`, not by a Flutter engine: the app deliberately
/// outlives its window, and history that stopped recording the moment you
/// closed the window would be history with holes in it.
final class ClipboardMonitor {
  static let shared = ClipboardMonitor()

  private static let interval: TimeInterval = 0.35

  /// Set by anything that marks its own pasteboard writes as not worth
  /// recording. Respected by every well-behaved clipboard manager, and it is
  /// how password managers ask not to be remembered.
  private static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
  private static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
  private static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

  private init() {}

  private let pasteboard = NSPasteboard.general
  private var timer: Timer?
  private var lastChangeCount = 0

  /// The change our own copy-back produced. Skipped once, so clicking a row
  /// does not push a duplicate of it back to the top of the list.
  private var suppressedChangeCount = -1

  func start() {
    guard timer == nil else { return }

    ClipboardStore.shared.load()
    lastChangeCount = pasteboard.changeCount

    let timer = Timer(timeInterval: Self.interval, repeats: true) { [weak self] _ in
      self?.poll()
    }
    // .common, so the tick survives menu tracking and window drags — otherwise
    // anything copied while a menu is open arrives late or not at all.
    RunLoop.main.add(timer, forMode: .common)
    self.timer = timer
  }

  func stop() {
    timer?.invalidate()
    timer = nil
  }

  /// Puts an entry back on the pasteboard, and arranges for the change it
  /// causes not to be recorded as a fresh copy.
  @discardableResult
  func copyToPasteboard(_ entry: ClipboardEntry) -> Bool {
    let store = ClipboardStore.shared
    pasteboard.clearContents()

    var wrote = false
    switch entry.kind {
    case .files:
      let urls = entry.paths.map { URL(fileURLWithPath: $0) as NSURL }
      wrote = !urls.isEmpty && pasteboard.writeObjects(urls)
    case .image:
      if let data = store.blobData(for: entry), let image = NSImage(data: data) {
        wrote = pasteboard.writeObjects([image])
      }
    case .richText:
      if let data = store.blobData(for: entry) {
        wrote = pasteboard.setData(data, forType: .rtf)
      }
      // Always leave a plain-text fallback: pasting rich text into a plain
      // field must not come out empty.
      if let text = store.fullText(for: entry) {
        wrote = pasteboard.setString(text, forType: .string) || wrote
      }
    case .text, .link:
      if let text = store.fullText(for: entry) {
        wrote = pasteboard.setString(text, forType: .string)
      }
    }

    suppressedChangeCount = pasteboard.changeCount
    lastChangeCount = pasteboard.changeCount
    return wrote
  }

  // MARK: - Polling

  private func poll() {
    let current = pasteboard.changeCount
    guard current != lastChangeCount else { return }
    lastChangeCount = current

    if current == suppressedChangeCount {
      suppressedChangeCount = -1
      return
    }

    guard ClipboardStore.shared.prefs.enabled else { return }
    capture()
  }

  private func capture() {
    let types = Set(pasteboard.types ?? [])

    // Refuse before reading anything. A concealed or transient write is one the
    // source app asked us not to keep, and honouring that half-way — storing it
    // redacted — is not honouring it.
    if types.contains(Self.concealed)
      || types.contains(Self.transient)
      || types.contains(Self.autoGenerated) {
      return
    }

    let source = NSWorkspace.shared.frontmostApplication
    let bundleId = source?.bundleIdentifier
    if let bundleId, ClipboardStore.shared.prefs.excludedBundleIds.contains(bundleId) { return }

    let now = Date().timeIntervalSince1970 * 1000
    let appName = source?.localizedName

    if let capture = readFiles(at: now, appName: appName, bundleId: bundleId) {
      ClipboardStore.shared.record(capture.entry, blob: capture.blob)
      return
    }
    if let capture = readText(types: types, at: now, appName: appName, bundleId: bundleId) {
      ClipboardStore.shared.record(capture.entry, blob: capture.blob)
      return
    }
    if let capture = readImage(at: now, appName: appName, bundleId: bundleId) {
      ClipboardStore.shared.record(capture.entry, blob: capture.blob)
    }
  }

  private typealias Capture = (entry: ClipboardEntry, blob: Data?)

  // MARK: - Readers
  //
  // Order matters and is not the order of the pasteboard's own type list.
  // Finder puts a string alongside its file URLs, a web page puts a rendered
  // TIFF alongside its text, and TextEdit puts plain text alongside its RTF.
  // Files first, then anything with real text, then images — so copying a
  // sentence off a web page stays a sentence and a screenshot stays an image.

  private func readFiles(at now: Double, appName: String?, bundleId: String?) -> Capture? {
    let options: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
    guard let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: options) as? [URL],
          !urls.isEmpty
    else { return nil }

    let paths = urls.map(\.path)
    let names = urls.map(\.lastPathComponent)
    let preview = names.count == 1
      ? names[0]
      : "\(names[0]) and \(names.count - 1) more"

    return (
      ClipboardEntry(
        id: Self.hash(of: Data(paths.joined(separator: "\n").utf8)),
        kind: .files,
        preview: preview,
        text: paths.joined(separator: "\n"),
        blobExtension: nil,
        byteCount: 0,
        characterCount: 0,
        paths: paths,
        pixelWidth: 0,
        pixelHeight: 0,
        sourceAppName: appName,
        sourceBundleId: bundleId,
        at: now,
        sensitive: false
      ),
      nil
    )
  }

  private func readText(
    types: Set<NSPasteboard.PasteboardType>,
    at now: Double,
    appName: String?,
    bundleId: String?
  ) -> Capture? {
    guard let text = pasteboard.string(forType: .string),
          !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    else { return nil }

    let rtf = types.contains(.rtf) ? pasteboard.data(forType: .rtf) : nil
    let sensitive = ClipboardRedaction.looksSensitive(text)

    let kind: ClipboardKind
    if rtf != nil {
      kind = .richText
    } else if Self.isLink(text) {
      kind = .link
    } else {
      kind = .text
    }

    // Rich text keeps its RTF in the blob and its plain fallback inline, so a
    // paste into a plain field still works when the blob is gone.
    let inline = kind == .richText || ClipboardStore.fitsInline(text)
    let blob: Data?
    let ext: String?
    if kind == .richText {
      blob = rtf
      ext = rtf == nil ? nil : "rtf"
    } else if inline {
      blob = nil
      ext = nil
    } else {
      blob = Data(text.utf8)
      ext = "txt"
    }

    return (
      ClipboardEntry(
        id: Self.hash(of: Data(text.utf8)),
        kind: kind,
        preview: Self.preview(of: text),
        text: inline ? text : nil,
        blobExtension: ext,
        byteCount: text.utf8.count,
        characterCount: text.count,
        paths: [],
        pixelWidth: 0,
        pixelHeight: 0,
        sourceAppName: appName,
        sourceBundleId: bundleId,
        at: now,
        sensitive: sensitive
      ),
      blob
    )
  }

  private func readImage(at now: Double, appName: String?, bundleId: String?) -> Capture? {
    guard ClipboardStore.shared.prefs.captureImages else { return nil }
    guard let tiff = pasteboard.data(forType: .tiff) ?? pasteboard.data(forType: .png),
          let rep = NSBitmapImageRep(data: tiff),
          let png = rep.representation(using: .png, properties: [:])
    else { return nil }

    let width = rep.pixelsWide
    let height = rep.pixelsHigh
    let overCeiling = png.count > ClipboardStore.shared.prefs.maxImageBytes

    return (
      ClipboardEntry(
        id: Self.hash(of: png),
        kind: .image,
        preview: "\(width) × \(height) image",
        text: nil,
        // An image over the ceiling keeps its row and loses its content: the
        // row still answers "did I copy that screenshot?", at no disk cost.
        blobExtension: overCeiling ? nil : "png",
        byteCount: png.count,
        characterCount: 0,
        paths: [],
        pixelWidth: width,
        pixelHeight: height,
        sourceAppName: appName,
        sourceBundleId: bundleId,
        at: now,
        sensitive: false
      ),
      overCeiling ? nil : png
    )
  }

  // MARK: - Helpers

  private static func hash(of data: Data) -> String {
    SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
  }

  /// A single line for the list, with runs of whitespace collapsed so a pasted
  /// code block does not render as one word and a lot of air.
  private static func preview(of text: String) -> String {
    let collapsed = text
      .components(separatedBy: .whitespacesAndNewlines)
      .filter { !$0.isEmpty }
      .joined(separator: " ")
    return collapsed.count <= 300 ? collapsed : String(collapsed.prefix(300)) + "…"
  }

  private static func isLink(_ text: String) -> Bool {
    let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
    guard !trimmed.contains(" "), trimmed.count < 2048 else { return false }
    guard let url = URL(string: trimmed), let scheme = url.scheme?.lowercased() else { return false }
    if scheme == "mailto" { return true }
    return ["http", "https", "ftp", "file"].contains(scheme) && url.host != nil
  }
}

/// Guesses whether a piece of text is something the user would not want sitting
/// in a list in plain sight.
///
/// A backstop, not a guarantee. The pasteboard's concealed marker is the real
/// mechanism and is checked first; this catches the secrets that arrive from a
/// terminal or an editor, which mark nothing. It is deliberately biased towards
/// false positives — a blurred row the user reveals costs a click, a missed one
/// costs a credential.
enum ClipboardRedaction {
  private static let patterns: [NSRegularExpression] = {
    let sources = [
      // Provider key shapes, which are stable enough to match literally.
      #"\bsk-[A-Za-z0-9_-]{20,}"#,
      #"\b(ghp|gho|ghu|ghs|ghr|github_pat)_[A-Za-z0-9_]{20,}"#,
      #"\bAKIA[0-9A-Z]{16}\b"#,
      #"\bxox[baprs]-[A-Za-z0-9-]{10,}"#,
      #"\bAIza[0-9A-Za-z_-]{35}\b"#,
      #"-----BEGIN [A-Z ]*PRIVATE KEY-----"#,
      // A JWT.
      #"\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}"#,
      // A credential sitting in a URL or a connection string.
      #"://[^/\s:@]+:[^/\s:@]+@"#,
      // An assignment whose name says secret and whose value is not empty.
      #"(?i)\b(pass(word|wd)?|secret|token|api[_-]?key|credential)\b\s*[:=]\s*\S{6,}"#,
    ]
    return sources.compactMap { try? NSRegularExpression(pattern: $0) }
  }()

  static func looksSensitive(_ text: String) -> Bool {
    // A whole document that happens to contain the word "password" is not a
    // secret; a short string that matches one of these almost always is.
    guard text.count <= 4096 else { return false }

    let range = NSRange(text.startIndex..., in: text)
    for pattern in patterns where pattern.firstMatch(in: text, range: range) != nil {
      return true
    }
    return containsCardNumber(text)
  }

  /// A Luhn-valid 13–19 digit run, ignoring the spaces and dashes people paste
  /// card numbers with.
  private static func containsCardNumber(_ text: String) -> Bool {
    var digits: [Int] = []

    func check() -> Bool {
      guard (13...19).contains(digits.count) else { return false }
      var sum = 0
      for (offset, digit) in digits.reversed().enumerated() {
        if offset % 2 == 1 {
          let doubled = digit * 2
          sum += doubled > 9 ? doubled - 9 : doubled
        } else {
          sum += digit
        }
      }
      return sum % 10 == 0
    }

    for character in text {
      if let value = character.wholeNumberValue, character.isNumber {
        digits.append(value)
        if digits.count > 19 { digits.removeFirst() }
      } else if character == " " || character == "-" {
        continue
      } else {
        if check() { return true }
        digits.removeAll()
      }
    }
    return check()
  }
}
