import 'package:tidy/core/design/app_icons.dart';
import 'package:flutter/widgets.dart';

/// Which part of the Mac a finding is about.
enum ProtectionArea {
  startup('Startup Items', 'What starts itself when you log in or boot up.'),
  extensions('Browser Extensions', 'What your browser extensions can reach.'),
  apps('Installed Apps', 'Who signed your apps, and where they came from.'),
  traces('Privacy Traces', 'What this Mac has written down about you.');

  const ProtectionArea(this.label, this.blurb);

  final String label;
  final String blurb;

  IconData get icon => switch (this) {
    ProtectionArea.startup => AppIcons.loginItems,
    ProtectionArea.extensions => AppIcons.browser,
    ProtectionArea.apps => AppIcons.applications,
    ProtectionArea.traces => AppIcons.privacy,
  };
}

/// How a finding reads at a glance.
///
/// **Deliberately not [SafetyLevel].** That enum's `safe` means "regenerated by
/// macOS or the owning app" — a statement about whether removing something is
/// reversible, which is a question this module never asks. Reusing it would also
/// drag `preselected` in, and nothing here is ever pre-ticked because nothing
/// here has a bulk action. Adding a case to it would change the landing page,
/// which renders `SafetyLevel.values` directly.
enum ProtectionVerdict {
  /// Everything we looked for came back ordinary.
  ordinary,

  /// One or more measured facts stand out. **Not an accusation** — the row says
  /// which fact and lets the reader decide.
  notable,

  /// We could not look. Never folded into either of the others.
  unverified,
}

/// One measured fact about one thing.
///
/// Never an opinion and never a list lookup — [label] is what macOS reported and
/// [detail] is what that means in plain words. If a fact cannot be written as
/// something a reader could go and check themselves, it does not belong here.
@immutable
class ProtectionFact {
  const ProtectionFact(this.label, this.detail, {this.notable = false});

  /// A denied read, in the one shape every area reports it.
  const ProtectionFact.unreadable(this.detail)
    : label = 'Could not read',
      notable = false;

  final String label;
  final String detail;

  /// Whether this is the kind of fact worth a second look. False for the
  /// ordinary ones — "Signed by Apple" is a fact and is not a finding.
  final bool notable;

  bool get isUnreadable => label == 'Could not read';
}

/// What can be done about a finding. The page turns each of these into a button
/// and nothing else does — a finding with no actions is a statement, which is a
/// legitimate thing for it to be.
enum ProtectionAction {
  reveal,
  disable,
  enable,
  remove,
  validate,
  assess,
  openSettings,
  openApps,

  /// Puts macOS's own "access data from other apps" dialog on screen.
  ///
  /// Its own action rather than something the page does on load, because with
  /// this permission the first read *is* the request — see
  /// `AppDataAccessService`. The row above the button is the explanation that
  /// has to come first.
  allowBrowserAccess,
}

/// One row on the Protection page.
@immutable
class ProtectionFinding {
  const ProtectionFinding({
    required this.id,
    required this.area,
    required this.title,
    required this.facts,
    this.subtitle = '',
    this.path,
    this.appPath,
    this.actions = const {},
    this.enabled,
  });

  /// Stable across refreshes — usually the path. What the ignore list stores.
  final String id;

  final ProtectionArea area;
  final String title;

  /// Where it lives, with `$HOME` collapsed to `~`.
  final String subtitle;

  final List<ProtectionFact> facts;
  final String? path;

  /// The owning `.app`, for its icon.
  final String? appPath;

  final Set<ProtectionAction> actions;

  /// Only startup items have an off switch; null everywhere else.
  final bool? enabled;

  /// Unreadable beats notable beats ordinary.
  ///
  /// That order is the point: "we could not check this" must never be shown as
  /// "this is fine", which is the same lie as a scanner reporting nothing found
  /// without having looked.
  ProtectionVerdict get verdict {
    if (facts.any((fact) => fact.isUnreadable)) {
      return ProtectionVerdict.unverified;
    }
    if (facts.any((fact) => fact.notable)) return ProtectionVerdict.notable;
    return ProtectionVerdict.ordinary;
  }

  /// The facts worth showing as chips — the notable ones, and anything that
  /// says we could not look. The ordinary ones are what the absence of a chip
  /// already says.
  List<ProtectionFact> get chips => [
    for (final fact in facts)
      if (fact.notable || fact.isUnreadable) fact,
  ];
}
